Server:
  RunMode: debug
  HttpPort: 8080 #your port
  ReadTimeout: 60
  WriteTimeout: 60
Database:
  DBType: mysql
  UserName: root
  Password: rootroot #your password
  Host: 127.0.0.1:3306
  DBName: chatroom
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
JWT:
  Secret: something #your secret
  Issuer: something #your issuer
  Expire: 7200
Chatroom:
  MessageQueueLength: 1024
